name_types = {
        'first': [
            'Tim',
            'James',
            'John',
            'Peter',
            'Samuel',
            'Aaron',
            'Connor',
            'Simon',
            'Sean',
            'Zach',
            'Martin',
            'Michael',
            'Guy',
            'Gary',
            'Louis',
            'Rufus',
            'Dennis',
            'Charles',
            'Adam',
            'Oscar',
            'Harvey',
            'Harry',
            'Terry',
            'William',
            'Basil',
            'Hugo',
            'Mateo',
            'Marco',
            'Rafael',
            'Federico',
            'Jaime',
            'Flynn',
            'Benito',
            'Manuel',
            'Lucien',
            'Franz',
            'Magnus',
            'Hubert',
            'Pablo',
            'Alejandro',
            'Lorenzo',
            'Stepan',
            'Dimitri',
            'Damien',
            'Ivan',
            'Serge',
            'Igor',
            'Leo',
            'Boris',
            'Vladimir',
            'Viktor',
            'Mikhail',
            'Nikolai',
            'Lev',
            'Simeon',
            'Valentin',
            'Alexei',
            'Xavier',
            'Zayn',
            'Altair',
            'Malik',
            'Zayd',
            'Mustafa',
            'Mohhamed',
            'Hamza',
            'Haruki',
            'Akito',
            'Hiroto',
            'Wei',
            'Hao',
            'Ding',
            'Ming',
            'Sarah',
            'Amy',
            'Charlotte',
            'Jane',
            'Jessica',
            'Jennifer',
            'Jenna',
            'Lucy',
            'Emily',
            'Zoe',
            'Elizabeth',
            'Amelia',
            'Hannah',
            'Anna',
            'Florence',
            'Lucia',
            'Luna',
            'Lana',
            'Maggie',
            'Vilma',
            'Freja',
            'Elise',
            'Rosalie',
            'Andrea',
            'Sandy',
            'Sofia',
            'Paloma',
            'Martina',
            'Bianca',
            'Martha',
            'Emma',
            'Maria',
            'Mary',
            'Sue',
            'Sharon',
            'Sara',
            'Heather',
            'Sophie',
            'June',
            'Julia',
            'Kiki',
            'Elaine',
            'Mia',
            'Mila',
            'Daniela',
            'Olivia',
            'Carmen',
            'Vega',
            'Karina',
            'Katerina',
            'Mia',
            'Sonia',
            'Irina',
            'Alisa',
            'Anastasia',
            'Anya',
            'Yasmin',
            'Jasmin',
            'Adiza',
            'Lila',
            'Zara',
            'Layla',
            'Inaya',
            'Kayla',
            'Yara',
            'Walaa',
            'Zora',
            'Alia',
            'Lulu',
            'Yukina',
            'Akari',
            'Min',
            'Hua',
            'Chun'
        ],
        'last': [
            'Smith',
            'Goldsmith',
            'Stewart',
            'Montogomery',
            'Kennedy',
            'Winters',
            'Roberts',
            'Myers',
            'Wilde',
            'Kavan',
            'Butler',
            'Davidson',
            'Blossom',
            'Knight',
            'Rogers',
            'White',
            'Henderson',
            'Rose',
            'Reid',
            'Carver',
            'Gomez',
            'Diaz',
            'Rodriguez',
            'Garcia',
            'Sanchez',
            'Lopez',
            'Martinez',
            'Alonso',
            'Ruiz',
            'Matisse',
            'Ocasio',
            'Bernard',
            'Allard',
            'Granger',
            'Picard',
            'Faucher',
            'Legrand',
            'Hemmingson',
            'Hastrup',
            'Dahl',
            'Holt',
            'Jacobsen',
            'Jepsen',
            'Kaas',
            'Karlsen',
            'Leth',
            'Bruun',
            'Dragunov',
            'Fedorov',
            'Ramos',
            'Ivanov',
            'Smirnov',
            'Petrov',
            'Sidorov',
            'Rukober',
            'Popov',
            'Sokolov',
            'Fyodorov',
            'Volkov',
            'Aziz',
            'Badr',
            'Bakir',
            'Faris',
            'Farouq',
            'Hamdi',
            'Isa',
            'Jabal',
            'Karim',
            'Khalid',
            'Mohammed',
            'Qasim',
            'Bassam',
            'Yusuf',
            'Shariq',
            'Wahed',
            'Satou',
            'Diwali',
            'Suzuki',
            'Yamamoto',
            'Nakamura',
            'Yoshida',
            'Yamada',
            'Matsumoto',
            'Li',
            'Wang',
            'Zhang',
            'Liu',
            'Chen',
            'Yang',
            'Zhao',
            'Sing',
            'Liren'
        ]
    }

resource_types = {
    'academic': {
        'prefix': [
            'A Treatise on ',
            'Some Notes on ',
            'On ',
            'The Results of ',
            'Analysis on ',
            'Notes on ',
            'Thoughts on ',
            'Some Thoughts on ',
            'Interpreting ',
            'Modern ',
            'The History of ',
            'Understanding ',
            'Advanced ',
            'Beginning with ',
            'A Guide to ',
            'Experts on ',
            'Dissecting ',
            'Trends in ',
            'Explaining ',
            'Advancements in ',
            'An Introduction to ',
            'Practical '
        ],
        'main': [
            'Neurobiology',
            'Philosophy of Mind',
            'Functional Programming',
            'Child Psychology',
            'Sports Therapy',
            'Microbiology',
            'Astrophysics',
            'Insect Studies',
            'Crimonology',
            'Anthropology',
            'Nanobiology',
            'Nanotechnology',
            'Embedded Systems',
            'Warfare Studies',
            'Python',
            'Evolution',
            'Object-oriented Programming',
            'Semantics',
            'European Languages',
            'Chinese',
            'Symbolism',
            'American Literature',
            'German',
            'Applied Mathematics',
            'Abstract Structures',
            'Engine Design',
            'Interpretive Dance',
            'Religions of Tribal Peoples',
            'Blacksmithing',
            'Logo Creation',
            'Accounting',
            'International Trade',
            'World Economics',
            'Animal Husbandry',
            'Banking',
            'Shakespeare',
            'Theatrical Works',
            'Method Acting',
            'Woodworking',
            'Nursing',
            'Homeopathy',
            'Aeronautical Engineering',
            'Business Studies',
            'C++',
            'Ancient Cultures',
            'Eastern Philosophy',
            'Chivalry',
            'Quantum Physics',
            'Emerging Technologies',
            'Architecture',
            'Archaeology',
            'Xenobiology',
            'Speleology',
            'Marine Biology',
            'Classical Music',
            'Music Theory',
            'Harmonics',
            'Computer Networking',
            'The King Arthur Mythology',
            'Dentistry',
            'Anesthesiology',
            'Astronomy',
            'Java',
            'Procedural Programming',
            'Data Structures',
            'Mythology'
        ],
        'suffix': [
            ' and Related Topics',
            ' with foreword from the author',
            ' the Collected Edition',
            ' for the Modern Scholar',
            ' In Practice'
        ]
    },
    'fiction': {
        'prefix': [
            'Another',
            'Only',
            'Ultimate',
            'Down',
            'Tales of the',
            'Memories of the',
            'Return to the',
            'Ashes of the',
            'Temptations of the',
            'Towards the',
            'Under the',
            'Over the',
            'Beneath the',
            'Visions of my',
            'Calling for the',
            'Oh',
            'Finding',
            'Seeking'
        ],
        'noun': [
            'Alley',
            'Edge',
            'House',
            'Space',
            'Point',
            'Sister',
            'Brother',
            'Spirit',
            'Height',
            'Sense',
            'Dream',
            'Trial',
            'Overground',
            'Underground',
            'Longing',
            'Trouble',
            'Love',
            'Death',
            'Wedding',
            'Rose',
            'Girl',
            'Boy',
            'Bone',
            'Remnant',
            'Past',
            'Shadow',
            'War',
            'Respect',
            'Soldier',
            'Lover',
            'Matador',
            'Member',
            'Attic',
            'Rug',
            'Agreement',
            'Piece',
            'Terrace',
            'Pot',
            'Cloak',
            'Tear',
            'Fabric',
            'Shot',
            'Vision',
            'Ship',
            'Waiter',
            'Hotel',
            'Barrier',
            'Bottle',
            'Barrel',
            'Pit',
            'Hovel',
            'Cape',
            'Stay',
            'Barkeep',
            'Grief',
            'Temptation',
            'Music',
            'Trap',
            'Hideout',
            'Bandit',
            'Revolver',
            'Resolution',
            'Tactic',
            'Marriage',
            'Husband',
            'Colour',
            'Craving',
            'Complexion',
            'Ocean',
            'Eye',
            'Hand',
            'Mind',
            'Rock',
            'Cliff',
            'Precipice',
            'Belt',
            'Brink',
            'Bank',
            'Place',
            'Price',
            'Vessel',
            'Time',
            'Wheel',
            'Warp',
            'Voyage'
        ],
        'adjective': [
            'Pointed',
            'Bloody',
            'Desperate',
            'Lovely',
            'Distant',
            'Otherwordly',
            'Red',
            'Velvet',
            'Shrouded',
            'Pink',
            'Muddy',
            'Cloudy',
            'Peaceful',
            'Partial',
            'Once',
            'Silent',
            'Loud',
            'Worthy',
            'Brave',
            'Sudden',
            'Mysterious',
            'Mirthless',
            'Grave',
            'Secret',
            'Yellow',
            'Crimson',
            'Smoking',
            'Crying',
            'Singing',
            'Laughing',
            'Ultimate',
            'Last',
            'Blue',
            'Dark',
            'Barren',
            'Wandering',
            'Travelling',
            'Perplexing',
            'Studded',
            'Silver',
            'Golden',
            'Grieving',
            'Joyless',
            'Joyful',
            'Little',
            'Big',
            'Tiny',
            'Scolding',
            'Smouldering',
            'Special',
            'Timid',
            'Empty'
        ],
        'adverb': [
            'Suddenly',
            'Sympathetically',
            'Provatively',
            'Piercingly',
            'Imperatively',
            'Partially',
            'Desperately',
            'Shamefully',
            'Sincerely',
            'Haltingly',
            'Finally',
            'Tentatively'
        ]
    },
    'non-fiction': {
        'prefix': [
            'My shocking story about ',
            'The truth about ',
            'One thing you should know about ',
            'One more thing you should know about ',
            'Lessons about ',
            'Finding out about ',
            'Learning and ',
            'Learning about ',
            'Survival guide: ',
            'What we learned from ',
            'The next step in ',
            'Up next: ',
            'Secrets of ',
            'Everything you wanted to know about ',
            'A review of ',
            'Taking a look at ',
            'Diving deeper into ',
            'A closer look at ',
            'The logical conclusion of ',
            'How to spot ',
            'Navigating '
        ],
        'subject': [
            'swimming',
            'boxing',
            'fencing',
            'farming',
            'gardening',
            'the Vietnam War',
            'the Korean War',
            'the Great Depression',
            'the Roaring 20s',
            'the school system',
            'pancakes',
            'parsnips',
            'British politics',
            'World War II',
            'the Great War',
            'the Russian Revolution',
            'NASA',
            'anime',
            'WWE',
            'the UFC',
            'dieting',
            'beauty products',
            'the kitchen sink',
            'samurai swords',
            'saber-tooth tigers',
            'polar bears',
            'the Antarctic',
            'the Arctic Circle',
            'ABBA',
            'dangerous predators',
            'the Big Bang',
            'black holes',
            'the Internet',
            'networking',
            'the Pharmaceutical Industry',
            'Seasonal Affective Disorder',
            'tobacco',
            'trombones',
            'serial killers',
            'fungi',
            'acting',
            'conspiracy theories',
            'the BBC',
            'reality TV',
            'cartoons',
            'karaoke',
            'the Great Wall of China',
            'dating culture in the US',
            'fine dining',
            'Marxism',
            'crop circles',
            'fast food',
            'fire prevention',
            'music festivals',
            'the floor of the ocean',
            'giant squids',
            'sanitation',
            'paranormal activity',
            'mainstream science',
            'earthquakes',
            'hurricanes',
            'charity work',
            'New York',
            'Tokyo',
            'London',
            'Moscow',
            'Paris',
            'Madrid',
            'trading',
            'SEO',
            'the great Global shift',
            'dairy products',
            'the meat industry',
            'addiction',
            'national debt',
            'the Bible',
            'mythology',
            'the dark ages',
            'hot air balloons',
            'jazz music',
            'K-pop',
            'lucid dreaming',
            'sleep deprivation',
            'working from home',
            'self-employment',
            'DIY',
            'hitchhiking',
            'raising a family',
            'robotics',
            'feudal Japan',
            'Cambodia',
            'cravings',
            'bird habitats',
            'the war on drugs',
            'Holywood'
        ],
        'suffix': [
            ' - a guide',
            ': a guide',
            ' - unanswered questions',
            ': what you need to know',
            ' for the ordinary reader',
            ' for dummies',
            ': a dark truth',
            ' - what we learned',
            ': what they do not tell you',
            ' - who would have thought?',
            ' for the uninititated',
            ' and other such things',
            ': weird but true'
        ],
        'biography-suffix': [
            ': the Good, the Bad, and the Ugly',
            ': A life lived',
            ': A life in Acting',
            ': A life in Service',
            ': A Life Story',
            ': A Giant',
            ': the Untold tales',
            ': an unofficial Biography',
            ': a Biography',
            ': a Legend',
            ': who were they really?',
            ': looking back'
        ],
        'complete-title': [
            'My Story',
            'My Life',
            'Self-Published',
            'Things I Used to Know',
            'Who Asked?',
            'The way we did it',
            'Unabridged',
            'Stories',
            'Memoirs',
            'Memories',
            'Looking Back',
            'The Whole Truth',
            'Delicious Recipes',
            'Feed a Family',
            'Us',
            'Me and Them',
            'Overcome',
            'Breathe',
            'Make Better Friends',
            'Taming the Lion',
            'Never Before',
            'Dreams',
            'In my Head',
            'Who Else?',
            'The Only One'
        ]
    }
}
