CREATE VIEW LoanOverdueDate AS 
SELECT * FROM Loan WHERE ReturnedTimeStamp != NULL AND CAST (CURRENT_TIMESTAMP AS DATE) - CAST (LoanedTimestamp AS DATE) > 14;

----

CREATE VIEW ShowFines AS 
SELECT * FROM Fine WHERE PaidTimeStamp = NULL;

------

CREATE VIEW OfferDueDate AS 
SELECT * FROM Offer WHERE CAST (CURRENT_TIMESTAMP AS DATE) - CAST (OfferedTimestamp AS DATE) > 2;